services:
  - type: web
    name: tvkkallavi
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
